/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Class;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luciano
 */
public class TelaHistorico extends javax.swing.JFrame {

    /**
     * Creates new form SelectChave
     */
    public TelaHistorico() {
        initComponents();
        //  ButtonTest();
    }

    public void ClickLinhaChave() {

        int linha = tbBuscaChave.getSelectedRow();
        String col_0 = String.valueOf(tbBuscaChave.getValueAt(linha, 0));
        String col_1 = String.valueOf(tbBuscaChave.getValueAt(linha, 1));
        String col_2 = String.valueOf(tbBuscaChave.getValueAt(linha, 2));

        testeNum.setText(col_0);
        testeNome.setText(col_1);
        testeDep.setText(col_2);

        int chave = Integer.parseInt(col_0);
        Hostorico(chave, tblChavePessoa);

    }

    public void Hostorico(int Chave, JTable tabela) {
        Class_Connection con = new Class_Connection();
        con.Conecta();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        tabela.getColumnModel().getColumn(0);
        if (Chave != 0) {

            try {
                PreparedStatement strComandoSQL;
                strComandoSQL = con.Conexao.prepareStatement("SELECT nome,cpf, telefone, empresa,dataSaida, horaSaida, horaRetorno, dataRetorno  FROM TBPessoa p\n"
                        + "INNER JOIN TBHistorico h\n"
                        + "ON p.idPessoa = h.idPessoa\n"
                        + "where idChave ="+Chave); // COMANDO OK. BUSCA POR NUMERO

                strComandoSQL.setCursorName(Integer.toString(Chave));
                con.rsBusca = strComandoSQL.executeQuery();
                while (con.rsBusca.next()) {
                    modelo.addRow(new Object[]{
                        con.rsBusca.getString(1),
                        con.rsBusca.getString(2),
                        con.rsBusca.getString(3),
                        con.rsBusca.getString(4),
                        con.rsBusca.getString(5),
                        con.rsBusca.getString(6),});
                }
                con.Comando.close();
                con.Conexao.close();
            } catch (SQLException Excecao) {
                JOptionPane.showMessageDialog(null, "ERRO AO OBTER DADOS NA BUSCA");
            }
        }

    }

    public void BuscaChave() {
        String Busca = null;
        Class_Connection con = new Class_Connection();
        con.Conecta();
        Class_Chave chave = new Class_Chave();

        Busca = txtBuscaChave.getText();
        chave.TabelaBuscaChave(tbBuscaChave, Busca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        testeNum = new javax.swing.JTextField();
        testeNome = new javax.swing.JTextField();
        testeDep = new javax.swing.JTextField();
        txtBuscaChave = new javax.swing.JTextField();
        btnBuscaChave = new javax.swing.JButton();
        FUNDO_CHAVE1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBuscaChave = new javax.swing.JTable();
        Fundo_Result_Busca = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChavePessoa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        testeNum.setEditable(false);
        testeNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        testeNum.setMaximumSize(new java.awt.Dimension(50, 90));
        jPanel1.add(testeNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 50, -1));

        testeNome.setEditable(false);
        jPanel1.add(testeNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 540, -1));

        testeDep.setEditable(false);
        testeDep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(testeDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 80, -1));

        txtBuscaChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaChaveActionPerformed(evt);
            }
        });
        txtBuscaChave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaChaveKeyPressed(evt);
            }
        });
        jPanel1.add(txtBuscaChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 330, 25));

        btnBuscaChave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/procurar.png"))); // NOI18N
        btnBuscaChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaChaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscaChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 40, 40));

        FUNDO_CHAVE1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        FUNDO_CHAVE1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSCAR CHAVE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(FUNDO_CHAVE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 420, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbBuscaChave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUM", "LOCAL", "DPTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBuscaChave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbBuscaChaveChaveMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbBuscaChave);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 410, 180));

        Fundo_Result_Busca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOCALIZADO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.add(Fundo_Result_Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 410, 200));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 380));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblChavePessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CPF", "TEL", "EMPRESA", "DATA SAIDA", "HORA SAIDA", "DATA RETORNO", "HORA RETORNO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblChavePessoa);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 800, 360));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 820, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1300, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbBuscaChaveChaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBuscaChaveChaveMousePressed
        // TODO add your handling code here:
        ClickLinhaChave();
    }//GEN-LAST:event_tbBuscaChaveChaveMousePressed

    private void txtBuscaChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaChaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaChaveActionPerformed

    private void txtBuscaChaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaChaveKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            BuscaChave();
    }//GEN-LAST:event_txtBuscaChaveKeyPressed

    private void btnBuscaChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaChaveActionPerformed
        // TODO add your handling code here:
        BuscaChave();
    }//GEN-LAST:event_btnBuscaChaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHistorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNDO_CHAVE1;
    private javax.swing.JPanel Fundo_Result_Busca;
    private javax.swing.JButton btnBuscaChave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbBuscaChave;
    private javax.swing.JTable tblChavePessoa;
    private javax.swing.JTextField testeDep;
    private javax.swing.JTextField testeNome;
    private javax.swing.JTextField testeNum;
    private javax.swing.JTextField txtBuscaChave;
    // End of variables declaration//GEN-END:variables
}
