/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Class.Class_Chave;
import Class.Class_Connection;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author luciano
 */
public class TelaAlteracaoChave extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlteracaoChave
     */
    public TelaAlteracaoChave() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbBuscaChave = new javax.swing.JTable();
        txtBuscaChave = new javax.swing.JTextField();
        btnBuscaChave = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        txtAtualDep = new javax.swing.JTextField();
        txtAtualLocal = new javax.swing.JTextField();
        txtAtualNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNovoNum = new javax.swing.JTextField();
        txtNovoLocal = new javax.swing.JTextField();
        txtNovoDep = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Fundo_Result_Busca = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        FUNDO_BUSCA_CHAVE = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        FUNDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbBuscaChave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUM", "LOCAL", "DPTO", "DISP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBuscaChave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbBuscaChaveMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbBuscaChave);
        if (tbBuscaChave.getColumnModel().getColumnCount() > 0) {
            tbBuscaChave.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 430, 180));

        txtBuscaChave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaChaveKeyPressed(evt);
            }
        });
        getContentPane().add(txtBuscaChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 340, 25));

        btnBuscaChave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/procurar.png"))); // NOI18N
        btnBuscaChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaChaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscaChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 40, 40));

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carraca.png"))); // NOI18N
        btnAlterar.setText("ALTERAR ");
        btnAlterar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 140, 50));

        txtAtualDep.setEditable(false);
        txtAtualDep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtAtualDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 100, 25));

        txtAtualLocal.setEditable(false);
        getContentPane().add(txtAtualLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 340, 25));

        txtAtualNum.setEditable(false);
        txtAtualNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtAtualNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 50, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DPTO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("LOCAL:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("NUM:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DADOS ATUAIS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 420, 130));

        txtNovoNum.setEditable(false);
        txtNovoNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtNovoNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 185, 50, 25));
        getContentPane().add(txtNovoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 215, 340, 25));

        txtNovoDep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtNovoDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 245, 100, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("NUM:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 185, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("LOCAL:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 215, -1, 20));

        Fundo_Result_Busca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOCALIZADO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        getContentPane().add(Fundo_Result_Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 430, 200));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("DPTO:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 245, -1, 20));

        FUNDO_BUSCA_CHAVE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSCAR CHAVE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        getContentPane().add(FUNDO_BUSCA_CHAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DADOS NOVOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 420, 120));

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lixo.png"))); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red));
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 140, 50));
        getContentPane().add(FUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BuscaChave() {
        String Busca = null;
        Class_Chave chave = new Class_Chave();
        Class_Connection connection = new Class_Connection();
        connection.Conecta();
        Busca = txtBuscaChave.getText();
        chave.TabelaBuscaChave(tbBuscaChave, Busca);
    }

    public void ClickLinha() {
        int linha = tbBuscaChave.getSelectedRow();
        String col_0 = String.valueOf(tbBuscaChave.getValueAt(linha, 0));
        String col_1 = String.valueOf(tbBuscaChave.getValueAt(linha, 1));
        String col_2 = String.valueOf(tbBuscaChave.getValueAt(linha, 2));

        txtAtualNum.setText(col_0);
        txtNovoNum.setText(col_0);
        txtAtualLocal.setText(col_1);
        txtAtualDep.setText(col_2);
    }

    private void btnBuscaChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaChaveActionPerformed
        // TODO add your handling code here:
        txtBuscaChave.setEditable(true);
        BuscaChave();
    }//GEN-LAST:event_btnBuscaChaveActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        try {
            String strNovoLocal = txtNovoLocal.getText();
            String strNovoDep = txtNovoDep.getText();

            int where = Integer.parseInt(txtAtualNum.getText());

            Class_Chave chave = new Class_Chave();
            chave.AlterarChave(strNovoLocal, strNovoDep, where);
            BuscaChave();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "CHAVE NÃO SELECIONADA", "MENSAGEM", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtBuscaChaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaChaveKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            BuscaChave();
    }//GEN-LAST:event_txtBuscaChaveKeyPressed

    private void tbBuscaChaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBuscaChaveMousePressed
        // TODO add your handling code here:
        ClickLinha();
    }//GEN-LAST:event_tbBuscaChaveMousePressed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        try {
            int where = Integer.parseInt(txtAtualNum.getText());
            int escolha = JOptionPane.showConfirmDialog(null, "A EXCLUSÃO NÃO PODERÁ SER DESFEITA! \nCONTINUAR?", "EXCLUIR", JOptionPane.YES_NO_OPTION);
            if (escolha == 0) {
                Class_Chave chave = new Class_Chave();
                chave.DeletarChave(where);
                JOptionPane.showMessageDialog(null, "EXCLUSÃO EFETUADA!", "MENSAGEM", JOptionPane.INFORMATION_MESSAGE);
                BuscaChave();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "CHAVE NÃO SELECIONADA", "MENSAGEM", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        TelaInicial tela1 = new TelaInicial();
        int zero = 0;     
        tela1.setJanelaAlteChave(zero);
    }//GEN-LAST:event_formWindowClosing

    public void Atualiza() {
        BuscaChave();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlteracaoChave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlteracaoChave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlteracaoChave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlteracaoChave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlteracaoChave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNDO;
    private javax.swing.JPanel FUNDO_BUSCA_CHAVE;
    private javax.swing.JPanel Fundo_Result_Busca;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscaChave;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbBuscaChave;
    private javax.swing.JTextField txtAtualDep;
    private javax.swing.JTextField txtAtualLocal;
    private javax.swing.JTextField txtAtualNum;
    private javax.swing.JTextField txtBuscaChave;
    private javax.swing.JTextField txtNovoDep;
    private javax.swing.JTextField txtNovoLocal;
    private javax.swing.JTextField txtNovoNum;
    // End of variables declaration//GEN-END:variables
}
