/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Class.Class_Cautela;
import Class.Class_Chave;
import Class.Class_DateTime;
import Class.Class_Connection;
import Class.Class_Pessoa;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author luciano
 */
public class TelaInicial extends javax.swing.JFrame {

    private static int janelaCaChave = 0;
    private static int janelaCaPessoa = 0;
    private static int janelaAlteChave = 0;
    private static int janelaAltePessoa = 0;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {

        initComponents();
        Boot();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Fundo_Result_Busca = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBuscaChave = new javax.swing.JTable();
        FUNDO_CHAVE1 = new javax.swing.JLabel();
        txtBuscaChave = new javax.swing.JTextField();
        btnBuscaChave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTotChave = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmUso = new javax.swing.JTable();
        Fundo_Em_Uso = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Fundo_Result_Busca1 = new javax.swing.JPanel();
        FUNDO = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbBuscaPessoa = new javax.swing.JTable();
        FUNDO_PESSOA = new javax.swing.JLabel();
        txtBuscaPessoa = new javax.swing.JTextField();
        btnBuscaPessoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotPessoas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JFOHoraSaida = new javax.swing.JFormattedTextField();
        JFODataSaida = new javax.swing.JFormattedTextField();
        btnRegistrar = new javax.swing.JButton();
        menuSuperior = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnCadastrarChave = new javax.swing.JMenuItem();
        btnCadastrarPessoa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnAlterarChave = new javax.swing.JMenuItem();
        btnAlterarPessoa = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnArquivos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAUTELA DE CHAVE");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fundo_Result_Busca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOCALIZADO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        Fundo_Result_Busca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbBuscaChave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUM", "LOCAL", "DPTO", "DISPONIVEL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBuscaChave.setShowGrid(true);
        tbBuscaChave.setSurrendersFocusOnKeystroke(true);
        tbBuscaChave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbBuscaChaveChaveMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbBuscaChave);
        if (tbBuscaChave.getColumnModel().getColumnCount() > 0) {
            tbBuscaChave.getColumnModel().getColumn(0).setMinWidth(0);
            tbBuscaChave.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbBuscaChave.getColumnModel().getColumn(0).setMaxWidth(50);
            tbBuscaChave.getColumnModel().getColumn(3).setMinWidth(0);
            tbBuscaChave.getColumnModel().getColumn(3).setPreferredWidth(20);
            tbBuscaChave.getColumnModel().getColumn(3).setMaxWidth(20);
        }

        Fundo_Result_Busca.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 500, 180));

        jPanel2.add(Fundo_Result_Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 500, 200));

        FUNDO_CHAVE1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        FUNDO_CHAVE1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSCAR CHAVE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.add(FUNDO_CHAVE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 90));

        txtBuscaChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaChaveActionPerformed(evt);
            }
        });
        txtBuscaChave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaChaveKeyPressed(evt);
            }
        });
        jPanel2.add(txtBuscaChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 400, 25));

        btnBuscaChave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/procurar.png"))); // NOI18N
        btnBuscaChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaChaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscaChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 40, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("CHAVES TOTAIS:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 25));

        txtTotChave.setEditable(false);
        txtTotChave.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        txtTotChave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotChave.setMaximumSize(new java.awt.Dimension(50, 55));
        jPanel2.add(txtTotChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 30, 25));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 330));

        tbEmUso.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tbEmUso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUM", "LOCAL", "NOME", "DATA SAÍDA", "HORA SAÍDA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEmUso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tbEmUso);
        if (tbEmUso.getColumnModel().getColumnCount() > 0) {
            tbEmUso.getColumnModel().getColumn(0).setMinWidth(0);
            tbEmUso.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbEmUso.getColumnModel().getColumn(0).setMaxWidth(50);
        }
        tbEmUso.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 450, 170));

        Fundo_Em_Uso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EM USO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        Fundo_Em_Uso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Fundo_Em_Uso, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 450, 200));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fundo_Result_Busca1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOCALIZADO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        Fundo_Result_Busca1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Fundo_Result_Busca1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Fundo_Result_Busca1.add(FUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 246, -1, -1));

        tbBuscaPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "TELEFONE", "EMPRESA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBuscaPessoa.setAlignmentX(10.0F);
        tbBuscaPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBuscaPessoaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbBuscaPessoa);
        if (tbBuscaPessoa.getColumnModel().getColumnCount() > 0) {
            tbBuscaPessoa.getColumnModel().getColumn(0).setMinWidth(0);
            tbBuscaPessoa.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbBuscaPessoa.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        Fundo_Result_Busca1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 502, 180));

        jPanel1.add(Fundo_Result_Busca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 500, 200));

        FUNDO_PESSOA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSCAR PESSOA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(FUNDO_PESSOA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 90));

        txtBuscaPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscaPessoaMouseClicked(evt);
            }
        });
        txtBuscaPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaPessoaKeyPressed(evt);
            }
        });
        jPanel1.add(txtBuscaPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 400, 25));

        btnBuscaPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/procurar.png"))); // NOI18N
        btnBuscaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaPessoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscaPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 40, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("PESSOAS TOTAIS:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 25));

        txtTotPessoas.setEditable(false);
        txtTotPessoas.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        txtTotPessoas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTotPessoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 30, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 520, 330));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("SAÍDA");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, 20));

        JFOHoraSaida.setEditable(false);
        try {
            JFOHoraSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFOHoraSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JFOHoraSaida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(JFOHoraSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 70, 25));

        JFODataSaida.setEditable(false);
        try {
            JFODataSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFODataSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JFODataSaida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(JFODataSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 90, 25));

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carraca.png"))); // NOI18N
        btnRegistrar.setText("REGISTRAR ");
        btnRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 150, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 1080, 630));

        jMenu1.setText("CADASTRAR");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        btnCadastrarChave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chave.png"))); // NOI18N
        btnCadastrarChave.setText("CHAVE");
        btnCadastrarChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarChaveActionPerformed(evt);
            }
        });
        jMenu1.add(btnCadastrarChave);

        btnCadastrarPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/do-utilizador.png"))); // NOI18N
        btnCadastrarPessoa.setText("PESSOA");
        btnCadastrarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(btnCadastrarPessoa);

        menuSuperior.add(jMenu1);

        jMenu2.setText("ALTERAÇÃO DE DADOS");

        btnAlterarChave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chave.png"))); // NOI18N
        btnAlterarChave.setText("CHAVE");
        btnAlterarChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarChaveActionPerformed(evt);
            }
        });
        jMenu2.add(btnAlterarChave);

        btnAlterarPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/do-utilizador.png"))); // NOI18N
        btnAlterarPessoa.setText("PESSOA");
        btnAlterarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(btnAlterarPessoa);

        menuSuperior.add(jMenu2);

        jMenu3.setText("CONFIGURAÇÃO");

        btnArquivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/base-de-dadosx24.png"))); // NOI18N
        btnArquivos.setText("ARQUIVOS");
        btnArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArquivosActionPerformed(evt);
            }
        });
        jMenu3.add(btnArquivos);

        menuSuperior.add(jMenu3);

        setJMenuBar(menuSuperior);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void btnCadastrarChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarChaveActionPerformed
        // TODO add your handling code here:
        if (janelaCaChave != 0) {
            JOptionPane.showMessageDialog(null, "JANELA JÁ ESTÁ ABERTA!");
        } else {
            new TelaCadastroChave().setVisible(true);
            janelaCaChave++;
        }
    }//GEN-LAST:event_btnCadastrarChaveActionPerformed

    private void btnCadastrarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPessoaActionPerformed
        // TODO add your handling code here:
        if (janelaCaPessoa != 0) {
            JOptionPane.showMessageDialog(null, "JANELA JÁ ESTÁ ABERTA!");
        } else {
            new TelaCadastroPessoa().setVisible(true);
            janelaCaPessoa++;
        }

    }//GEN-LAST:event_btnCadastrarPessoaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Cautela();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscaChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaChaveActionPerformed
        // TODO add your handling code here:
        BuscaChave();
    }//GEN-LAST:event_btnBuscaChaveActionPerformed

    private void btnBuscaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaPessoaActionPerformed
        // TODO add your handling code here:
        BuscaPessoa();
    }//GEN-LAST:event_btnBuscaPessoaActionPerformed

    private void btnAlterarChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarChaveActionPerformed
        // TODO add your handling code here:
        if (janelaAlteChave != 0) {
            JOptionPane.showMessageDialog(null, "JANELA JÁ ESTÁ ABERTA!");
        } else {
            new TelaAlteracaoChave().setVisible(true);
            janelaAlteChave++;
        }
    }//GEN-LAST:event_btnAlterarChaveActionPerformed

    private void tbBuscaChaveChaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBuscaChaveChaveMousePressed
        // TODO add your handling code here:       
        ClickLinhaChave();
    }//GEN-LAST:event_tbBuscaChaveChaveMousePressed

    private void txtBuscaChaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaChaveKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            BuscaChave();
    }//GEN-LAST:event_txtBuscaChaveKeyPressed

    private void txtBuscaChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaChaveActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtBuscaChaveActionPerformed

    private void txtBuscaPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscaPessoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaPessoaMouseClicked

    private void txtBuscaPessoaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaPessoaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            BuscaPessoa();
    }//GEN-LAST:event_txtBuscaPessoaKeyPressed

    private void btnAlterarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPessoaActionPerformed
        // TODO add your handling code here:
        if (janelaAltePessoa != 0) {
            JOptionPane.showMessageDialog(null, "JANELA JÁ ESTÁ ABERTA!");
        } else {

            new TelaAlteracaoPessoa().setVisible(true);
            janelaAltePessoa++;
        }
    }//GEN-LAST:event_btnAlterarPessoaActionPerformed

    private void btnArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArquivosActionPerformed
        AlteraChaminhoBD();
    }//GEN-LAST:event_btnArquivosActionPerformed

    private void tbBuscaPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBuscaPessoaMouseClicked
        // TODO add your handling code here:
        clickLinhaPessoa();
    }//GEN-LAST:event_tbBuscaPessoaMouseClicked
    private void Boot() {
        Class_Chave chave = new Class_Chave();
        chave.EmUso(tbEmUso);
      //  ChecaCaminhoBD();
        BuscaChave();
        BuscaPessoa();

    }

    public void Cautela() {
        Class_Cautela cautela = new Class_Cautela();
        Class_DateTime time = new Class_DateTime();
        int linhac = tbBuscaChave.getSelectedRow();
        String dispo = String.valueOf(tbBuscaChave.getValueAt(linhac, 3));
        if (dispo == "true") {
            try {

                String col_0c = String.valueOf(tbBuscaChave.getValueAt(linhac, 0));
                int linhap = tbBuscaPessoa.getSelectedRow();
                String col_0p = String.valueOf(tbBuscaPessoa.getValueAt(linhap, 0));
                
                String dataS = time.getDia();
                String horaS = time.getHora();

                cautela.inseret(Integer.parseInt(col_0p), Integer.parseInt(col_0c), dataS, horaS);
                Boot();
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "DADOS NÃO SELECIONADOS!", "MENSAGEM", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "CHAVE NÃO DISPONÍVEL!");
        }

    }

    public void ChecaCaminhoBD() {
        Class_Connection con = new Class_Connection();
        String caminho = con.getLocalBD();
        if (caminho.contains("null") || !caminho.contains("C:")) {
            String LocalBD = JOptionPane.showInputDialog("CAMINHO DO BANCO DE DADOS NÃO ENCONTRADO: \nCOLAR CAMINHO: ");
            if (LocalBD == null) {
                JOptionPane.showMessageDialog(null, "DEIXANDO EM BRANCO NÃO SERÁ POSSIVEL LER E EDITAR OS REGISTROS!");
            } else {
                con.setLocalBD(LocalBD);
                con.SaveConfig();
            }
        } else {
            JOptionPane.showMessageDialog(null, "BANCO DE DADOS CARREGADO :)", "MENSAGEM", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void AlteraChaminhoBD() {
        Class_Connection con = new Class_Connection();
        String caminho = con.getLocalBD();
        if (caminho.contains(".accdb")) {
            int confirma = JOptionPane.showConfirmDialog(null, "O PROCESSO NÃO PODERÁ SER DESFEITO!\n CONTINUAR? ",
                    "CANCELAR", JOptionPane.YES_NO_OPTION);
            if (confirma == 0) {
                String LocalBD = JOptionPane.showInputDialog("Colar caminho do banco de dados");
                con.setLocalBD(LocalBD);
                con.SaveConfig();
            } else {
                JOptionPane.showMessageDialog(null, "DEIXANDO EM BRANCO NÃO SERÁ POSSIVEL LER E EDITAR OS REGISTROS!");
            }
        } else {
            ChecaCaminhoBD();
        }
    }

    public void ClickLinhaChave() {

        int linha = tbBuscaChave.getSelectedRow();
        String col_0 = String.valueOf(tbBuscaChave.getValueAt(linha, 0));
        String col_1 = String.valueOf(tbBuscaChave.getValueAt(linha, 1));
        String col_2 = String.valueOf(tbBuscaChave.getValueAt(linha, 2));

    }

    public void clickLinhaPessoa() {
        int linha = tbBuscaPessoa.getSelectedRow();
        String col_0 = String.valueOf(tbBuscaPessoa.getValueAt(linha, 0));
        String col_1 = String.valueOf(tbBuscaPessoa.getValueAt(linha, 1));
        String col_2 = String.valueOf(tbBuscaPessoa.getValueAt(linha, 2));
        String col_3 = String.valueOf(tbBuscaPessoa.getValueAt(linha, 3));
        String col_4 = String.valueOf(tbBuscaPessoa.getValueAt(linha, 4));

    }

    public void BuscaChave() {
        String Busca = null;
        Class_Connection con = new Class_Connection();
        con.Conecta();
        Class_Chave chave = new Class_Chave();

        Busca = txtBuscaChave.getText();
        chave.TabelaBuscaChave(tbBuscaChave, Busca);
        txtTotChave.setText(Integer.toString(chave.TotLinhas()));
    }

    public void BuscaPessoa() {
        String Busca = null;
        Class_Connection con = new Class_Connection();
        con.Conecta();
        Class_Pessoa pessoa = new Class_Pessoa();

        Busca = txtBuscaPessoa.getText();
        pessoa.TabelaBuscaPessoa(tbBuscaPessoa, Busca);
        txtTotPessoas.setText(Integer.toString(pessoa.TotLinhas()));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNDO;
    private javax.swing.JLabel FUNDO_CHAVE1;
    private javax.swing.JLabel FUNDO_PESSOA;
    private javax.swing.JPanel Fundo_Em_Uso;
    private javax.swing.JPanel Fundo_Result_Busca;
    private javax.swing.JPanel Fundo_Result_Busca1;
    private javax.swing.JFormattedTextField JFODataSaida;
    private javax.swing.JFormattedTextField JFOHoraSaida;
    private javax.swing.JMenuItem btnAlterarChave;
    private javax.swing.JMenuItem btnAlterarPessoa;
    private javax.swing.JMenuItem btnArquivos;
    private javax.swing.JButton btnBuscaChave;
    private javax.swing.JButton btnBuscaPessoa;
    private javax.swing.JMenuItem btnCadastrarChave;
    private javax.swing.JMenuItem btnCadastrarPessoa;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuBar menuSuperior;
    private javax.swing.JTable tbBuscaChave;
    private javax.swing.JTable tbBuscaPessoa;
    private javax.swing.JTable tbEmUso;
    private javax.swing.JTextField txtBuscaChave;
    private javax.swing.JTextField txtBuscaPessoa;
    private javax.swing.JTextField txtTotChave;
    private javax.swing.JTextField txtTotPessoas;
    // End of variables declaration//GEN-END:variables
}
